name: Tests

on:
  push:
    branches:
      -dev
      -main
      -master

jobs:
  hello-world:
  run-on ubuntu-20.04
  steps:
    - name: Say hello world
      shell: bash
      run: echo Welcome to the github